version: '3.7'

services:

  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    env_file:
      - '.env'
    ports:
      - "5673:5672"
      - "15672:15672"

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "src.app:flask_app"
    env_file:
      - '.env'
    volumes:
      - '.:/flask_celery_rabbitmq'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -A wsgi_app.celery --loglevel=info --pool=solo
    env_file:
      - '.env'
    volumes:
      - '.:/flask_celery_rabbitmq'
      
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbit:5672/
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
